### ISSUE TITLE
Doesn't react properly when a mod replies to a message

### ISSUE THREAD

**Issue by noticemechris** [Nobelz/SpartanBot#17]
**Problem:**
When a mod replies to a message, bot does not react to the emoji corresponding to the message author's tag. Meanwhile, if a normal user replies to someone's message, bot will react with the appropriate corresponding emoji to the author. [Example of problem in a message.](https://discord.com/channels/669280377680035842/700108433197760572/800588833137098782) | [Image link of message.](https://media.discordapp.net/attachments/700108433197760572/800595572071464960/unknown.png)

**Expected:**
Reacts with the emoji corresponding to the author's user ID. [Example of the bot reacting to a normal user.](https://discord.com/channels/669280377680035842/700108433197760572/800595140254892053) | [Image link of message.](https://media.discordapp.net/attachments/700108433197760572/800595676592734248/unknown.png)

**Priority:**
Critical

**Justification:**
If it's not fixed in two hours Howdy will ban me. He feels humiliated as he can't assert dominance.

**Projected loss of revenue:**
$1000000000000000 in Quarter One

**Comment by Nobelz** [comment]
Please duplicate this with other mods and not just with Howdy. The emoji will **only** be replied to if Howdy replies with a ping. If the reply has no ping, there will be no emoji reacted to. I believe the problem is not the fact that he's a mod but the fact that he's not replying with a ping. Please confirm this.

**Comment by noticemechris** [comment]
Yup, that's the issue. You need to reply with a ping for the bot to react, it was just a weird coincidence that the mods had it turned off. Closing issue.
